### ISSUE TITLE
是否适合移动端的支付呢？

### ISSUE THREAD

**Issue by mlc0202** [ihaolin/wepay#1]
首先赞一下作者的项目，实实在在降低了支付接入的门槛，但看测试用例，都是面向pc的，那当前项目是否也适合移动端的支付呢？

**Comment by ihaolin** [comment]
对于微信，JS支付，动态二维码支付均亲测过，APP移动端由于环境问题，未能放到移动端亲测，但微信支付都是统一接口，只是各支付方式返回结果又所差异，均已封装为对应的Response:
[JsPayResponse](https://github.com/ihaolin/wepay/blob/master/wepay-core/src/main/java/me/hao0/wepay/model/pay/JsPayResponse.java)，[AppPayResponse](https://github.com/ihaolin/wepay/blob/master/wepay-core/src/main/java/me/hao0/wepay/model/pay/AppPayResponse.java)，移动端支付只需通过AppPayResponse再发起对应客户端请求即可，若对接过程有错误，请提issue。

**Comment by mlc0202** [comment]
好的，谢谢
