### ISSUE TITLE
doPost 和doHttpsPost

### ISSUE THREAD

**Issue by fccfmichael** [ihaolin/wepay#11]
在doVerifySign时应该在效验结果false的时候throw个runtimeException？ 或者直接返回false。

**Comment by ihaolin** [comment]
Done.

**Comment by fccfmichael** [comment]
有一个小疑问，Response统一您觉得可以么或者合适么？（只针对tradetype为jsapi和app进行统一下response）

**Comment by ihaolin** [comment]
这个不太合适吧，app和js支付的结果是不一样的。
