### ISSUE TITLE
AppPayResponse的paySign有问

### ISSUE THREAD

**Issue by JimmyLincole** [ihaolin/wepay#3]
AppPayResponse 的“签名”属性命名为 paySign 是有其他考虑么？谢谢

**Comment by ihaolin** [comment]
其实没什么特别用意，只是提示下是客户端发起支付时，需要用的签名。

**Comment by JimmyLincole** [comment]
谢谢回复！

可能昨晚我的表述不太清楚，其实是想问：paySign 不命名 为 sign 是否有其他考虑？封装好格式，不需要客户端重新封装。

昨晚没留意到 package 这个关键字，因此除了封装为 Map返回，其他情况客户端还是免不了需要将服务器返回的 json 重新封装(即将 pkg -> package, paySign -> sign)

**Comment by ihaolin** [comment]
恩明白，可以通过注解映射为package和sign，后期会修复下这个地方。
